language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install:
  - pip install mock
  - pip install coveralls
script: coverage run --include gcm/gcm.py gcm/test.py
after_success:
    coveralls
